# Generated by Django 4.1.3 on 2023-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_review', models.CharField(max_length=100)),
                ('author', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('image_review', models.ImageField(upload_to='movie/images/')),
            ],
        ),
    ]
