# Generated by Django 4.1.3 on 2023-04-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_review',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
