# Generated by Django 4.1.3 on 2023-04-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_review_text_review_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(blank=True),
        ),
    ]
